# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magicsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magic_Wand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('image', models.ImageField(default=None, null=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Mahou_Shoujo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('image', models.ImageField(default=None, null=True, upload_to='photos')),
                ('age', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='magic_wand',
            name='mahou_shoujo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicsite.Mahou_Shoujo'),
        ),
    ]
