# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 12:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magicsite', '0003_auto_20180525_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Mahou_Shoujo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mahou_shoujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicsite.Mahou_Shoujo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Question_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_type', models.CharField(default='', max_length=1)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_Set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicsite.Question_Set')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
