# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magicsite', '0005_auto_20180607_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic_wand',
            name='mahou_shoujo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicsite.Mahou_Shoujo'),
        ),
    ]
